package com.codebook.datastructure.impl;

import com.codebook.datastructure.interfaces.ExpressionTree;

/**
 * TODO: Insert description here. (generated by oud)
 */
public class AlgebraExpressionTree implements ExpressionTree {

}
